// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Showcase.mvc.Data;
using System;

namespace Showcase.mvc.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20180619012447_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Showcase.mvc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category_Id");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Showcase.mvc.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Addr1");

                    b.Property<string>("Addr2");

                    b.Property<string>("Blurb");

                    b.Property<string>("City");

                    b.Property<int>("Client_Id");

                    b.Property<string>("Created");

                    b.Property<string>("Email");

                    b.Property<string>("Freetxt");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("Tel");

                    b.Property<string>("Url");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Showcase.mvc.Models.ClientCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Category_Id");

                    b.Property<int>("Client_Id");

                    b.HasKey("Id");

                    b.ToTable("ClientCategories");
                });

            modelBuilder.Entity("Showcase.mvc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
